# Generated by Django 4.1 on 2023-01-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Lifelog',
            old_name='start_datetime',
            new_name='start_datetime'
        ),
        migrations.RenameField(
            model_name='Lifelog',
            old_name='end_datetime',
            new_name='end_datetime'
        ),
        migrations.RenameField(
            model_name='Lifelog',
            old_name='updated_at',
            new_name='updated_at'
        ),
    ]
