# Generated by Django 4.1 on 2022-11-20 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifelog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
