# Generated by Django 4.1 on 2022-11-20 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0002_lifelog_created_at_alter_lifelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
