# Generated by Django 4.1 on 2023-02-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0003_lifelog_color_lifelog_detail_tag_memo_lifelog_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='user',
            new_name='created_by',
        ),
    ]
