# Generated by Django 4.1 on 2022-11-20 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0003_alter_lifelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 20, 12, 14, 22, 338003, tzinfo=datetime.timezone.utc)),
        ),
    ]
