# Generated by Django 4.1 on 2023-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0004_rename_user_tag_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
