# Generated by Django 4.1 on 2022-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0007_alter_lifelog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifelog',
            name='event',
            field=models.CharField(blank=True, default='aaa', max_length=100),
        ),
    ]
