# Generated by Django 4.1 on 2022-11-21 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0009_alter_lifelog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifelog',
            name='endDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='lifelog',
            name='staDate',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
