# Generated by Django 4.1 on 2022-11-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifelog', '0010_lifelog_enddate_lifelog_stadate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifelog',
            name='date',
        ),
    ]
